import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import AboutSection from '../components/AboutSection'
import AboutSignupSection from '../components/AboutSignupSection'
import Carousel from '../components/Carousel'
import Navbar from '../components/Navbar'
import './index.css'

const sections = [
  {
    image: 'amoeba-forward@2x.png',
    title: 'Water quality information is pretty complex and hard to digest...',
    body: (
      <p>That’s why we’ve created this dashboard so you can see what’s happening in your river at any given time. Our scientists have combed the data and created a system for understanding when it’s good, when it’s bad, and when it's something in between.</p>
    )
  },
  {
    image: 'amoeba-mission@2x.png',
    title: 'Design has the power to transform communities.',
    body: (
      <p>+ POOL is changing the relationship with the water around us. We have a vision in which people that represent the diversity of New York City are swimming in and around Manhattan safely, enjoying free and safe access to the river.</p>
    ),
    cta: <a className='about-section__cta' href='https://pluspool.org/donate/'>Donate to support our work</a>
  },
  {
    image: 'amoeba-community@2x.png',
    title: 'Learn about the communities that support the health of our waterways.',
    body: (
      <p>+ POOL is made up of an incredible group of people that are all working together to make sure we have access to our rivers for swimming. Friends of + POOL send ideas, lend expertise, volunteer, support fundraising, and advocate for + POOL and the ideas generated by it.</p>
    )
  },
  {
    image: 'amoeba-jumpin@2x.png',
    title: 'It’s time to get to know your river better.',
    body: (
      <p>How warm was the water today? What’s turbidity? What’s pH? How is enterococci different from E. coli? Dive into the dashboard and find out!</p>
    ),
    cta: <Link><a className='about-section__cta' href='/'>Go to the dashboard</a></Link>
  }
]

const AboutPage = () => {
  return (
    <main className='page' data-template='about'>
      {sections.map((section, index) => (
          <>
            <AboutSection side={index % 2 === 0 ? 'left' : 'right'} {...section} />
            {index === 2 && (
              <>
                <Carousel items={[0, 1, 2, 3]} />
                <AboutSignupSection title='Join the movement!' cta='Sign up for our newsletter' />
              </>
            )}
          </>
      ))}
    </main>
  )
}

export default AboutPage
